package cs455.overlay.wireformats;

public enum MessageType {
	
	OVERLAY_NODE_SENDS_REGISTRATION,
	REGISTRY_REPORTS_REGISTRATION_STATUS,
	
	REGISTRY_SENDS_NODE_MANIFEST,
	NODE_REPORTS_OVERLAY_SETUP_STATUS,
	
	REGISTRY_REQUESTS_TAST_INITIATE,
	OVERLAY_NODE_SENDS_DATA,
	OVERLAY_NODE_REPORTS_TASK_FINISHED,
	
	REGISTRY_REQUESTS_TRAFFIC_SUMMARY,
	OVERLAY_NODE_REPORTS_TRAFFIC_SUMMARY,
	
}
